Update all non-major dependencies (#85)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Type | Update | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|---|---|
|  |  | lockFileMaintenance | All locks refreshed | [![age](https://developer.mend.io/api/mc/badges/age///?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption///?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility////?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence////?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [aws-cdk](https://togithub.com/aws/aws-cdk) ([source](https://togithub.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk)) | devDependencies | minor | [`2.115.0` -> `2.116.1`](https://renovatebot.com/diffs/npm/aws-cdk/2.115.0/2.116.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/aws-cdk/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/aws-cdk/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/aws-cdk/2.115.0/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/aws-cdk/2.115.0/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [aws-cdk-lib](https://togithub.com/aws/aws-cdk) ([source](https://togithub.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib)) | dependencies | minor | [`2.115.0` -> `2.116.1`](https://renovatebot.com/diffs/npm/aws-cdk-lib/2.115.0/2.116.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/aws-cdk-lib/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/aws-cdk-lib/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/aws-cdk-lib/2.115.0/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/aws-cdk-lib/2.115.0/2.116.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [@aws-sdk/client-secrets-manager](https://togithub.com/aws/aws-sdk-js-v3/tree/main/clients/client-secrets-manager) ([source](https://togithub.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-secrets-manager)) | dependencies | minor | [`3.478.0` -> `3.480.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-secrets-manager/3.478.0/3.480.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2fclient-secrets-manager/3.480.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2fclient-secrets-manager/3.480.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2fclient-secrets-manager/3.478.0/3.480.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2fclient-secrets-manager/3.478.0/3.480.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

🔧 This Pull Request updates lock files to use the latest dependency versions.

---

### Release Notes

<details>
<summary>aws/aws-cdk (aws-cdk)</summary>

### [`v2.116.1`](https://togithub.com/aws/aws-cdk/releases/tag/v2.116.1)

[Compare Source](https://togithub.com/aws/aws-cdk/compare/v2.116.0...v2.116.1)

##### Bug Fixes

-   **core:** core constructs fail with `Error: Cannot find module '../dist/core/<file>.generated'` ([#&#8203;28467](https://togithub.com/aws/aws-cdk/issues/28467)) ([e8be128](https://togithub.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933)), closes [#&#8203;28251](https://togithub.com/aws/aws-cdk/issues/28251) [#&#8203;28465](https://togithub.com/aws/aws-cdk/issues/28465)

***

##### Alpha modules (2.116.1-alpha.0)

### [`v2.116.0`](https://togithub.com/aws/aws-cdk/releases/tag/v2.116.0)

[Compare Source](https://togithub.com/aws/aws-cdk/compare/v2.115.0...v2.116.0)

##### Features

-   **apigateway:** validate integrationHttpMethod with non-MOCK integration types ([#&#8203;28316](https://togithub.com/aws/aws-cdk/issues/28316)) ([93cb6e4](https://togithub.com/aws/aws-cdk/commit/93cb6e4399fe0e2de67050f10920ec7a1eda34e1))
-   **ec2:** support creating key pairs ([#&#8203;28138](https://togithub.com/aws/aws-cdk/issues/28138)) ([6b3caff](https://togithub.com/aws/aws-cdk/commit/6b3caff7ac4321ca79e70821991de041d33eaa7c)), closes [#&#8203;5252](https://togithub.com/aws/aws-cdk/issues/5252)
-   **ecr:** Add emptyOnDelete CloudFormation property to Repository L2 construct ([#&#8203;28233](https://togithub.com/aws/aws-cdk/issues/28233)) ([a175da8](https://togithub.com/aws/aws-cdk/commit/a175da8ec1f4d6149efdfe05749d77ae104842d4)), closes [#&#8203;24572](https://togithub.com/aws/aws-cdk/issues/24572) [#&#8203;28196](https://togithub.com/aws/aws-cdk/issues/28196)
-   **ecr:** tag pattern list for lifecycle policy ([#&#8203;28432](https://togithub.com/aws/aws-cdk/issues/28432)) ([aa075cd](https://togithub.com/aws/aws-cdk/commit/aa075cd07a892e6c1d5243d5526e2c8658b98621))
-   **ecs:** log retention for FireLensLogDriver ([#&#8203;28354](https://togithub.com/aws/aws-cdk/issues/28354)) ([52a5579](https://togithub.com/aws/aws-cdk/commit/52a5579aa52c88bb289a7a9677c35385763c8fff)), closes [/github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts#L816](https://togithub.com/aws//github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts/issues/L816) [/github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts#L170](https://togithub.com/aws//github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ecs/lib/firelens-log-router.ts/issues/L170) [#&#8203;28258](https://togithub.com/aws/aws-cdk/issues/28258)
-   **ecs:** Support specifying revision of task definition ([#&#8203;27036](https://togithub.com/aws/aws-cdk/issues/27036)) ([de0d77b](https://togithub.com/aws/aws-cdk/commit/de0d77b2075506f3c28e657fa072a0bffc8c734a)), closes [#&#8203;26983](https://togithub.com/aws/aws-cdk/issues/26983)
-   **events:** add multiple event bus policies on a single event bus ([#&#8203;27340](https://togithub.com/aws/aws-cdk/issues/27340)) ([4dde502](https://togithub.com/aws/aws-cdk/commit/4dde5021a4e69de0ca2e49226ef0d2cde76d4235)), closes [#&#8203;24671](https://togithub.com/aws/aws-cdk/issues/24671)
-   **rds:** support aurora mysql 3.05.1 ([#&#8203;28370](https://togithub.com/aws/aws-cdk/issues/28370)) ([986db38](https://togithub.com/aws/aws-cdk/commit/986db38842c901bfe50098b36d78d6e3a6befdf1))
-   **ses:** add scalingMode property to dedicated ip pool ([#&#8203;28392](https://togithub.com/aws/aws-cdk/issues/28392)) ([c687778](https://togithub.com/aws/aws-cdk/commit/c6877788f7abd19b4dcc792d5fa73fc118410efd)), closes [#&#8203;27418](https://togithub.com/aws/aws-cdk/issues/27418)
-   **sns:** delivery status logging configuration ([#&#8203;28433](https://togithub.com/aws/aws-cdk/issues/28433)) ([36bb696](https://togithub.com/aws/aws-cdk/commit/36bb6967ad28a84b68e7b9ea5d5facadf0de4297)), closes [#&#8203;21971](https://togithub.com/aws/aws-cdk/issues/21971)
-   **stepfunctions:** CustomState addCatch ([#&#8203;28422](https://togithub.com/aws/aws-cdk/issues/28422)) ([cf923bc](https://togithub.com/aws/aws-cdk/commit/cf923bc4eacd3bb0efdc469708dc389a67d38bcc)), closes [#&#8203;25798](https://togithub.com/aws/aws-cdk/issues/25798)
-   **stepfunctions:** support Map ItemProcessor ([#&#8203;27913](https://togithub.com/aws/aws-cdk/issues/27913)) ([ac41730](https://togithub.com/aws/aws-cdk/commit/ac417301348f3bc2f0b7352c032802c2aff8d721)), closes [#&#8203;27878](https://togithub.com/aws/aws-cdk/issues/27878)
-   **stepfunctions-tasks:** EMR createCluster command support OnDemandSpecification ([#&#8203;27791](https://togithub.com/aws/aws-cdk/issues/27791)) ([73a5e74](https://togithub.com/aws/aws-cdk/commit/73a5e740e7556c8b59111ab4602125ac78a5364f)), closes [#&#8203;27761](https://togithub.com/aws/aws-cdk/issues/27761)
-   implement code generated handler framework ([#&#8203;28251](https://togithub.com/aws/aws-cdk/issues/28251)) ([1a9c30e](https://togithub.com/aws/aws-cdk/commit/1a9c30e55e58203bd0a61de82711cf10f1e04851)), closes [#&#8203;27303](https://togithub.com/aws/aws-cdk/issues/27303)
-   update AWS Service Spec ([#&#8203;28407](https://togithub.com/aws/aws-cdk/issues/28407)) ([fcb701c](https://togithub.com/aws/aws-cdk/commit/fcb701ceb7288be5307a0f9c12826a13d97251b7))

##### Bug Fixes

-   **core:** messages from `annotations.ts` can show up as `[object Object]` ([#&#8203;28414](https://togithub.com/aws/aws-cdk/issues/28414)) ([3e6f10d](https://togithub.com/aws/aws-cdk/commit/3e6f10ddfdf93147f3d488de2965f7e263bd1713))
-   **custom-resources:** cannot set logging for state machine generated in CompleteHandler ([#&#8203;27310](https://togithub.com/aws/aws-cdk/issues/27310)) ([bfeef00](https://togithub.com/aws/aws-cdk/commit/bfeef00c5e1d99415ff2135054e35acc5e9f6b93)), closes [#&#8203;27283](https://togithub.com/aws/aws-cdk/issues/27283)
-   **ecs-patterns:** taskDefinition ignored by queueProcessingFargateService ([#&#8203;28220](https://togithub.com/aws/aws-cdk/issues/28220)) ([5d6b8ee](https://togithub.com/aws/aws-cdk/commit/5d6b8eefc66d326325673bda2b86b72aa4579199)), closes [#&#8203;27360](https://togithub.com/aws/aws-cdk/issues/27360)
-   **eks:** neuron plugin not added with addNodegroupCapacity() ([#&#8203;27909](https://togithub.com/aws/aws-cdk/issues/27909)) ([b87212b](https://togithub.com/aws/aws-cdk/commit/b87212b9fe2064b97d8935db49e6d78e183c2fd8))
-   **events-targets:** imported sqs queue cannot be used as a rule dlq ([#&#8203;28165](https://togithub.com/aws/aws-cdk/issues/28165)) ([#&#8203;28285](https://togithub.com/aws/aws-cdk/issues/28285)) ([588b106](https://togithub.com/aws/aws-cdk/commit/588b1064c289295c5acce1b991ef8dcd7c8bec3f))
-   **iam:** importedRoleStackSafeDefaultPolicyName feature flag results in excessively long IAM policy names ([#&#8203;27548](https://togithub.com/aws/aws-cdk/issues/27548)) ([4f88db6](https://togithub.com/aws/aws-cdk/commit/4f88db691652274eb1b3119c8b1dccb196b29928)), closes [#&#8203;27409](https://togithub.com/aws/aws-cdk/issues/27409) [#&#8203;24441](https://togithub.com/aws/aws-cdk/issues/24441)
-   **logs:** adding a resource policy statement with `AnyPrincipal` fails ([#&#8203;27787](https://togithub.com/aws/aws-cdk/issues/27787)) ([0b2ba1c](https://togithub.com/aws/aws-cdk/commit/0b2ba1c5d807ce8dfc390ea3b0ca5a1e39636315)), closes [#&#8203;27783](https://togithub.com/aws/aws-cdk/issues/27783)
-   **s3-notifications:** multiple notifications doesn't work ([#&#8203;28132](https://togithub.com/aws/aws-cdk/issues/28132)) ([37be7b9](https://togithub.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8))
-   **secretsmanager:** cannot set hourly rotation ([#&#8203;28303](https://togithub.com/aws/aws-cdk/issues/28303)) ([09cb003](https://togithub.com/aws/aws-cdk/commit/09cb003fb917714c0dc88b47cd05893c2a816d45)), closes [#&#8203;28261](https://togithub.com/aws/aws-cdk/issues/28261)
-   **secretsmanager:** hosted rotation with fromSecretNameV2() does not create correct iam policy ([#&#8203;28379](https://togithub.com/aws/aws-cdk/issues/28379)) ([4ab5bb2](https://togithub.com/aws/aws-cdk/commit/4ab5bb2e9aab4cee4e8a2bcd81871254f2c3065f)), closes [#&#8203;28308](https://togithub.com/aws/aws-cdk/issues/28308)

***

#### Alpha modules (2.116.0-alpha.0)

##### Features

-   **scheduler:** flexible time windows ([#&#8203;28098](https://togithub.com/aws/aws-cdk/issues/28098)) ([6554e48](https://togithub.com/aws/aws-cdk/commit/6554e48908662de31aa5dba4578007c857c2403d))
-   **scheduler-targets:** add CodePipeline as target for scheduler ([#&#8203;27799](https://togithub.com/aws/aws-cdk/issues/27799)) ([8c44f32](https://togithub.com/aws/aws-cdk/commit/8c44f3298f6bd6d5b2b081eeef50296d6f716a2d)), closes [#&#8203;27449](https://togithub.com/aws/aws-cdk/issues/27449)

##### Bug Fixes

-   **integ-tests:** apply correct IAM policy to waiterProvider ([#&#8203;28424](https://togithub.com/aws/aws-cdk/issues/28424)) ([c488035](https://togithub.com/aws/aws-cdk/commit/c488035db893532c6aca97c59717a351539fa2ec)), closes [40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts#L136](https://togithub.com/40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts/issues/L136) [40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts#L247](https://togithub.com/40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts/issues/L247) [#&#8203;27865](https://togithub.com/aws/aws-cdk/issues/27865)
-   **lambda-python-alpha:** pipenv lock -r is no longer supported ([#&#8203;28317](https://togithub.com/aws/aws-cdk/issues/28317)) ([f85f486](https://togithub.com/aws/aws-cdk/commit/f85f486d34e51c4e5d6a8b68b16a35a14f431329)), closes [#&#8203;28015](https://togithub.com/aws/aws-cdk/issues/28015) [/github.com/pypa/pipenv/blob/main/CHANGELOG.md#2022813-2022-08-13](https://togithub.com/aws//github.com/pypa/pipenv/blob/main/CHANGELOG.md/issues/2022813-2022-08-13) [#&#8203;28015](https://togithub.com/aws/aws-cdk/issues/28015)

</details>

<details>
<summary>aws/aws-sdk-js-v3 (@&#8203;aws-sdk/client-secrets-manager)</summary>

### [`v3.480.0`](https://togithub.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-secrets-manager/CHANGELOG.md#34800-2023-12-22)

[Compare Source](https://togithub.com/aws/aws-sdk-js-v3/compare/v3.478.0...v3.480.0)

##### Features

-   **client-secrets-manager:** Update endpoint rules and examples. ([b9a4897](https://togithub.com/aws/aws-sdk-js-v3/commit/b9a4897c3fd274794de9c27e91688d325fcbc40b))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 5am on sunday" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/SvenKirschbaum/aws-utils).